env:
  browser: true
  commonjs: true
  es6: true
extends:
  - eslint:recommended
  - google
globals:
  process: false
parserOptions:
  ecmaVersion: 8
  ecmaFeatures:
    experimentalObjectRestSpread: true
    jsx: true
  sourceType: module
plugins:
  - react
  - import
rules:
  indent:
    - error
    - 2
  linebreak-style:
    - off
  max-len: [2, {code: 120, tabWidth: 2, ignoreUrls: true}]
  quotes:
    - error
    - single
  semi:
    - error
    - never

  no-console: 0
  no-unused-vars:
    - 2
    - args: 'none'
      varsIgnorePattern: "_|React"


  import/no-unresolved: 2
  import/named: 2
  import/namespace: 2
  import/default: 2
  import/export: 2

settings:
  import/parser: babel-eslint
